name: TextWrap
version: 1.1.0.${build.number}
description: Automatic word wrapping chat plugin for Bukkit-based Minecraft servers.
authors: [CraftFire, Contex, Wulfspider]
website: http://www.craftfire.com

main: com.craftfire.textwrap.TextWrap
